### ISSUE TITLE
Set an explicit caching policy

### ISSUE THREAD

**Issue by karifrederiksen** [LinusPhoenix/raidsimp#21]
Caddy has some default caching which leads to people having to force-clear their browser caches for every release.

Caching is fine for assets that include hashes in their names, such as the Javascript chunks. Caching images is probably fine for now since we never edit them - we can start hashing images once we start editing them.

`index.html`  on the other hand can't be hashed since it is referred to by name in the Caddyfile, and since we can't add a hash to its name and it's the root of our application, we must disable caching for it. Maybe `stale-while-revalidate` is appropriate though.

**Comment by LinusPhoenix** [comment]
Released in [1.0.0](https://github.com/LinusPhoenix/raidsimp/releases/tag/1.0.0)
